name: Gopher Things
on: [push]

jobs:
  test: 
    name: "run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1'
        run: go test ./...
